#!/bin/bash
# CacheCloud 辅助 Redis（assist）一键安装/启动
# 在服务器上执行，例如：cd /root/redis/redis-6.2.13 && bash setup-assist-redis.sh
set -euo pipefail

# 必须显式提供，不设默认口令
ASSIST_PASSWORD="${ASSIST_PASSWORD:?请设置 ASSIST_PASSWORD}"
REDIS_SRC="${REDIS_SRC:-$(pwd)}"
DATA_DIR="${DATA_DIR:-/var/lib/cachecloud-assist-redis}"
CONF="${CONF:-/etc/cachecloud-assist-redis.conf}"
PIDFILE="${PIDFILE:-/var/run/cachecloud-assist-redis.pid}"
LOGFILE="${LOGFILE:-/var/log/cachecloud-assist-redis.log}"

REDIS_SERVER="${REDIS_SRC}/src/redis-server"
REDIS_CLI="${REDIS_SRC}/src/redis-cli"

if [[ ! -x "${REDIS_SERVER}" ]]; then
  echo "ERROR: 未找到 ${REDIS_SERVER}，请在 redis 源码目录执行，或设置 REDIS_SRC"
  exit 1
fi

if ss -lntp 2>/dev/null | grep -q ':6379'; then
  echo "WARN: 6379 已被占用，请先确认是否为旧 assist Redis："
  ss -lntp | grep 6379 || true
  echo "若需替换，请先停止占用 6379 的进程后再运行本脚本。"
  exit 1
fi

mkdir -p "${DATA_DIR}"
chmod 700 "${DATA_DIR}"

cat > "${CONF}" <<EOF
# CacheCloud assist Redis - generated by setup-assist-redis.sh
bind 127.0.0.1
port 6379
requirepass ${ASSIST_PASSWORD}
daemonize yes
dir ${DATA_DIR}
pidfile ${PIDFILE}
logfile ${LOGFILE}
protected-mode yes
maxmemory 512mb
maxmemory-policy allkeys-lru
save ""
appendonly no
EOF

echo "==> 启动 assist Redis ..."
"${REDIS_SERVER}" "${CONF}"
sleep 1

if ! ss -lntp | grep -q ':6379'; then
  echo "ERROR: 启动失败，请查看 ${LOGFILE}"
  exit 1
fi

PONG=$("${REDIS_CLI}" -h 127.0.0.1 -p 6379 -a "${ASSIST_PASSWORD}" PING 2>/dev/null || true)
if [[ "${PONG}" != "PONG" ]]; then
  echo "ERROR: PING 失败"
  exit 1
fi

echo "OK: assist Redis 已启动"
echo "  host: 127.0.0.1"
echo "  port: 6379"
echo "  password: ${ASSIST_PASSWORD}"
echo "  config: ${CONF}"
echo "  data: ${DATA_DIR}"
echo ""
echo "application-online.yml 请配置："
echo "  cachecloud.redis.main.host: 127.0.0.1"
echo "  cachecloud.redis.main.port: 6379"
echo "  cachecloud.redis.main.password: ${ASSIST_PASSWORD}"
