spring:
  application:
    name: cloud.cachecloud-web.open.online
    import: classpath:spring/spring.xml

server:
  port: 80
  domain: ${SERVER_DOMAIN:http://127.0.0.1:80}

cachecloud:
  primary:
    url: ${CACHECLOUD_PRIMARY_URL:jdbc:mysql://127.0.0.1:3306/redis_manager?useUnicode=true&characterEncoding=UTF8&autoReconnect=true&connectTimeout=3000&socketTimeout=10000&serverTimezone=Asia/Shanghai}
    user: ${CACHECLOUD_PRIMARY_USER:root}
    password: ${CACHECLOUD_PRIMARY_PASSWORD:}
    initialPoolSize: 10
    maxPoolSize: 50
  redis:
    main:
      host: ${CACHECLOUD_REDIS_MAIN_HOST:127.0.0.1}
      port: ${CACHECLOUD_REDIS_MAIN_PORT:6379}
      password: ${CACHECLOUD_REDIS_MAIN_PASSWORD:}
  web:
    clients: 127.0.0.1
  kafka:
    enabled: false
    bootstrap-servers: 192.168.222.101:9092
    topicName: xxxxx
aof:
  rewrite:
    ignore-appIds:
