/**
 * Redis 配置项元数据：官方默认值 + 作用说明。
 *
 * 默认值不是手写的，而是启动一个未加任何自定义参数的 redis:6.2.13 实例、
 * 执行 CONFIG GET * 采集下来的，因此与官方默认严格一致。
 *
 * 注意：默认值随大版本会有出入（如 io-threads 为 6.0 新增、save 的默认策略 7.0 有调整）。
 * 表中没有的配置项（新版本新增、或模块注入）默认值显示为 "-"，不会误导为"已改动"。
 */
export const REDIS_CONFIG_DEFAULTS: Record<string, string> = {
  "acl-pubsub-default": "allchannels",
  "aclfile": "",
  "acllog-max-len": "128",
  "active-defrag-cycle-max": "25",
  "active-defrag-cycle-min": "1",
  "active-defrag-ignore-bytes": "104857600",
  "active-defrag-max-scan-fields": "1000",
  "active-defrag-threshold-lower": "10",
  "active-defrag-threshold-upper": "100",
  "active-expire-effort": "1",
  "activedefrag": "no",
  "activerehashing": "yes",
  "always-show-logo": "no",
  "aof-load-truncated": "yes",
  "aof-rewrite-incremental-fsync": "yes",
  "aof-use-rdb-preamble": "yes",
  "aof_rewrite_cpulist": "",
  "appendfilename": "appendonly.aof",
  "appendfsync": "everysec",
  "appendonly": "no",
  "auto-aof-rewrite-min-size": "67108864",
  "auto-aof-rewrite-percentage": "100",
  "bgsave_cpulist": "",
  "bind": "",
  "bio_cpulist": "",
  "client-output-buffer-limit": "normal 0 0 0 slave 268435456 67108864 60 pubsub 33554432 8388608 60",
  "client-query-buffer-limit": "1073741824",
  "cluster-allow-reads-when-down": "no",
  "cluster-allow-replica-migration": "yes",
  "cluster-announce-bus-port": "0",
  "cluster-announce-ip": "",
  "cluster-announce-port": "0",
  "cluster-announce-tls-port": "0",
  "cluster-enabled": "no",
  "cluster-migration-barrier": "1",
  "cluster-node-timeout": "15000",
  "cluster-replica-no-failover": "no",
  "cluster-replica-validity-factor": "10",
  "cluster-require-full-coverage": "yes",
  "cluster-slave-no-failover": "no",
  "cluster-slave-validity-factor": "10",
  "crash-log-enabled": "yes",
  "crash-memcheck-enabled": "yes",
  "daemonize": "no",
  "databases": "16",
  "dbfilename": "dump.rdb",
  "dir": "/data",
  "disable-thp": "yes",
  "dynamic-hz": "yes",
  "gopher-enabled": "no",
  "hash-max-ziplist-entries": "512",
  "hash-max-ziplist-value": "64",
  "hll-sparse-max-bytes": "3000",
  "hz": "10",
  "ignore-warnings": "",
  "io-threads": "1",
  "io-threads-do-reads": "no",
  "jemalloc-bg-thread": "yes",
  "key-load-delay": "0",
  "latency-monitor-threshold": "0",
  "lazyfree-lazy-eviction": "no",
  "lazyfree-lazy-expire": "no",
  "lazyfree-lazy-server-del": "no",
  "lazyfree-lazy-user-del": "no",
  "lazyfree-lazy-user-flush": "no",
  "lfu-decay-time": "1",
  "lfu-log-factor": "10",
  "list-compress-depth": "0",
  "list-max-ziplist-size": "-2",
  "logfile": "",
  "loglevel": "notice",
  "lua-replicate-commands": "yes",
  "lua-time-limit": "5000",
  "masterauth": "",
  "masteruser": "",
  "maxclients": "10000",
  "maxmemory": "0",
  "maxmemory-eviction-tenacity": "10",
  "maxmemory-policy": "noeviction",
  "maxmemory-samples": "5",
  "min-replicas-max-lag": "10",
  "min-replicas-to-write": "0",
  "min-slaves-max-lag": "10",
  "min-slaves-to-write": "0",
  "no-appendfsync-on-rewrite": "no",
  "notify-keyspace-events": "",
  "oom-score-adj": "no",
  "oom-score-adj-values": "0 200 800",
  "pidfile": "",
  "port": "6379",
  "proc-title-template": "{title} {listen-addr} {server-mode}",
  "protected-mode": "no",
  "proto-max-bulk-len": "536870912",
  "rdb-del-sync-files": "no",
  "rdb-key-save-delay": "0",
  "rdb-save-incremental-fsync": "yes",
  "rdbchecksum": "yes",
  "rdbcompression": "yes",
  "repl-backlog-size": "1048576",
  "repl-backlog-ttl": "3600",
  "repl-disable-tcp-nodelay": "no",
  "repl-diskless-load": "disabled",
  "repl-diskless-sync": "no",
  "repl-diskless-sync-delay": "5",
  "repl-ping-replica-period": "10",
  "repl-ping-slave-period": "10",
  "repl-timeout": "60",
  "replica-announce-ip": "",
  "replica-announce-port": "0",
  "replica-announced": "yes",
  "replica-ignore-maxmemory": "yes",
  "replica-lazy-flush": "no",
  "replica-priority": "100",
  "replica-read-only": "yes",
  "replica-serve-stale-data": "yes",
  "requirepass": "",
  "sanitize-dump-payload": "no",
  "save": "3600 1 300 100 60 10000",
  "server_cpulist": "",
  "set-max-intset-entries": "512",
  "set-proc-title": "yes",
  "slave-announce-ip": "",
  "slave-announce-port": "0",
  "slave-ignore-maxmemory": "yes",
  "slave-lazy-flush": "no",
  "slave-priority": "100",
  "slave-read-only": "yes",
  "slave-serve-stale-data": "yes",
  "slaveof": "",
  "slowlog-log-slower-than": "10000",
  "slowlog-max-len": "128",
  "stop-writes-on-bgsave-error": "yes",
  "stream-node-max-bytes": "4096",
  "stream-node-max-entries": "100",
  "supervised": "no",
  "syslog-enabled": "no",
  "syslog-facility": "local0",
  "syslog-ident": "redis",
  "tcp-backlog": "511",
  "tcp-keepalive": "300",
  "timeout": "0",
  "tls-auth-clients": "yes",
  "tls-ca-cert-dir": "",
  "tls-ca-cert-file": "",
  "tls-cert-file": "",
  "tls-ciphers": "",
  "tls-ciphersuites": "",
  "tls-client-cert-file": "",
  "tls-client-key-file": "",
  "tls-client-key-file-pass": "",
  "tls-cluster": "no",
  "tls-dh-params-file": "",
  "tls-key-file": "",
  "tls-key-file-pass": "",
  "tls-port": "0",
  "tls-prefer-server-ciphers": "no",
  "tls-protocols": "",
  "tls-replication": "no",
  "tls-session-cache-size": "20480",
  "tls-session-cache-timeout": "300",
  "tls-session-caching": "yes",
  "tracking-table-max-keys": "1000000",
  "unixsocket": "",
  "unixsocketperm": "0",
  "use-exit-on-panic": "no",
  "watchdog-period": "0",
  "zset-max-ziplist-entries": "128",
  "zset-max-ziplist-value": "64"
}

/** 配置项作用的简短说明，用于配置查询页的「配置说明」列 */
export const REDIS_CONFIG_DESCRIPTIONS: Record<string, string> = {
  "acl-pubsub-default": "新建 ACL 用户默认可访问的频道范围",
  "aclfile": "外部 ACL 规则文件路径",
  "acllog-max-len": "ACL 安全日志保留条数",
  "active-defrag-cycle-max": "主动碎片整理占用 CPU 的上限百分比",
  "active-defrag-cycle-min": "主动碎片整理占用 CPU 的下限百分比",
  "active-defrag-ignore-bytes": "碎片小于该字节数时不触发整理",
  "active-defrag-max-scan-fields": "单次整理扫描的最大字段数",
  "active-defrag-threshold-lower": "启动碎片整理的碎片率下限(%)",
  "active-defrag-threshold-upper": "碎片整理火力全开的碎片率上限(%)",
  "active-expire-effort": "过期键主动清理的积极程度，越大越激进",
  "activedefrag": "是否开启主动内存碎片整理",
  "activerehashing": "是否在空闲时渐进式 rehash 主哈希表",
  "always-show-logo": "启动时是否打印 ASCII LOGO",
  "aof-load-truncated": "加载被截断的 AOF 时是否继续启动",
  "aof-rewrite-incremental-fsync": "AOF 重写时是否每 4MB 增量刷盘",
  "aof-use-rdb-preamble": "AOF 重写是否以 RDB 格式作为前导(混合持久化)",
  "aof_rewrite_cpulist": "AOF 重写子进程绑定的 CPU 核",
  "appendfilename": "AOF 文件名",
  "appendfsync": "AOF 刷盘策略：always/everysec/no",
  "appendonly": "是否开启 AOF 持久化",
  "auto-aof-rewrite-min-size": "触发 AOF 自动重写的最小文件体积",
  "auto-aof-rewrite-percentage": "AOF 相对上次重写增长该百分比后触发重写",
  "bgsave_cpulist": "RDB 子进程绑定的 CPU 核",
  "bind": "监听的网卡地址",
  "bio_cpulist": "后台 IO 线程绑定的 CPU 核",
  "client-output-buffer-limit": "客户端输出缓冲区上限(普通/从库/订阅)",
  "client-query-buffer-limit": "单个客户端查询缓冲区上限",
  "cluster-allow-reads-when-down": "集群不可用时是否仍允许读",
  "cluster-allow-replica-migration": "是否允许从库自动迁移到缺从库的主库",
  "cluster-announce-bus-port": "对外通告的集群总线端口",
  "cluster-announce-ip": "对外通告的 IP(NAT/容器环境必填)",
  "cluster-announce-port": "对外通告的服务端口",
  "cluster-announce-tls-port": "对外通告的 TLS 端口",
  "cluster-enabled": "是否以集群模式运行",
  "cluster-migration-barrier": "主库至少保留几个从库才允许迁走",
  "cluster-node-timeout": "节点失联多久判定为故障(毫秒)",
  "cluster-replica-no-failover": "是否禁止该从库发起故障转移",
  "cluster-replica-validity-factor": "从库数据陈旧度容忍系数，越小越严格",
  "cluster-require-full-coverage": "槽位不全时是否整体停止服务",
  "cluster-slave-no-failover": "cluster-replica-no-failover 的旧别名",
  "cluster-slave-validity-factor": "cluster-replica-validity-factor 的旧别名",
  "crash-log-enabled": "崩溃时是否输出崩溃日志",
  "crash-memcheck-enabled": "崩溃时是否做内存检查",
  "daemonize": "是否以守护进程方式启动",
  "databases": "数据库数量(集群模式下仅 0 号库可用)",
  "dbfilename": "RDB 文件名",
  "dir": "数据文件(RDB/AOF)存放目录",
  "disable-thp": "是否禁用透明大页(建议禁用以避免延迟毛刺)",
  "dynamic-hz": "是否按连接数动态调整 hz",
  "gopher-enabled": "是否启用 Gopher 协议支持",
  "hash-max-ziplist-entries": "hash 使用紧凑编码的最大字段数",
  "hash-max-ziplist-value": "hash 使用紧凑编码的最大值长度",
  "hll-sparse-max-bytes": "HyperLogLog 稀疏编码的最大字节数",
  "hz": "后台任务(过期清理等)每秒执行次数",
  "ignore-warnings": "启动时忽略的告警类型",
  "io-threads": "网络 IO 线程数",
  "io-threads-do-reads": "IO 线程是否也处理读请求",
  "jemalloc-bg-thread": "是否启用 jemalloc 后台回收线程",
  "key-load-delay": "加载键时的人为延迟(调试用)",
  "latency-monitor-threshold": "延迟监控采样阈值(毫秒)，0 为关闭",
  "lazyfree-lazy-eviction": "内存淘汰时是否异步释放",
  "lazyfree-lazy-expire": "键过期时是否异步释放",
  "lazyfree-lazy-server-del": "服务端隐式删除时是否异步释放",
  "lazyfree-lazy-user-del": "DEL 命令是否异步释放",
  "lazyfree-lazy-user-flush": "FLUSHALL/FLUSHDB 是否异步释放",
  "lfu-decay-time": "LFU 计数衰减周期(分钟)",
  "lfu-log-factor": "LFU 计数增长的对数因子",
  "list-compress-depth": "list 两端不压缩的节点数",
  "list-max-ziplist-size": "list 单个节点的最大条目数或体积",
  "logfile": "日志文件路径，空为标准输出",
  "loglevel": "日志级别",
  "lua-replicate-commands": "Lua 脚本以命令效果而非脚本本身复制",
  "lua-time-limit": "Lua 脚本执行告警阈值(毫秒)",
  "masterauth": "连接主库使用的密码",
  "masteruser": "连接主库使用的用户名(ACL)",
  "maxclients": "最大客户端连接数",
  "maxmemory": "最大可用内存，0 为不限制",
  "maxmemory-eviction-tenacity": "淘汰工作的努力程度，越大越激进",
  "maxmemory-policy": "内存达上限时的淘汰策略",
  "maxmemory-samples": "淘汰算法每次采样的键数",
  "min-replicas-max-lag": "从库最大延迟秒数，超出则主库拒写",
  "min-replicas-to-write": "主库继续写入所需的最少健康从库数",
  "min-slaves-max-lag": "min-replicas-max-lag 的旧别名",
  "min-slaves-to-write": "min-replicas-to-write 的旧别名",
  "no-appendfsync-on-rewrite": "重写期间是否暂停 AOF 刷盘以降低阻塞",
  "notify-keyspace-events": "键空间通知的事件类型",
  "oom-score-adj": "是否调整进程的 OOM 评分",
  "oom-score-adj-values": "主/从/后台进程的 OOM 评分值",
  "pidfile": "PID 文件路径",
  "port": "服务监听端口",
  "proc-title-template": "进程标题模板",
  "protected-mode": "保护模式，未设密码时仅允许本机访问",
  "proto-max-bulk-len": "单个请求/回复的最大体积",
  "rdb-del-sync-files": "无持久化时同步完成后是否删除临时 RDB",
  "rdb-key-save-delay": "保存键时的人为延迟(调试用)",
  "rdb-save-incremental-fsync": "生成 RDB 时是否每 4MB 增量刷盘",
  "rdbchecksum": "RDB 是否写入 CRC64 校验和",
  "rdbcompression": "RDB 是否压缩字符串",
  "repl-backlog-size": "复制积压缓冲区大小，决定断线可增量重连的窗口",
  "repl-backlog-ttl": "无从库后积压缓冲区保留秒数",
  "repl-disable-tcp-nodelay": "复制链路是否合并小包(省带宽但增延迟)",
  "repl-diskless-load": "从库是否绕过磁盘直接加载 RDB",
  "repl-diskless-sync": "主库是否无盘发送 RDB",
  "repl-diskless-sync-delay": "无盘复制前的等待秒数，用于合并多个从库",
  "repl-ping-replica-period": "主库向从库发送 PING 的间隔(秒)",
  "repl-ping-slave-period": "repl-ping-replica-period 的旧别名",
  "repl-timeout": "复制超时时间(秒)",
  "replica-announce-ip": "从库对外通告的 IP",
  "replica-announce-port": "从库对外通告的端口",
  "replica-announced": "从库是否出现在 INFO/SENTINEL 的从库列表中",
  "replica-ignore-maxmemory": "从库是否忽略 maxmemory 自行淘汰",
  "replica-lazy-flush": "从库全量同步前是否异步清库",
  "replica-priority": "故障转移选主优先级，0 表示永不当选",
  "replica-read-only": "从库是否只读",
  "replica-serve-stale-data": "与主库断开时从库是否继续提供旧数据",
  "requirepass": "访问密码，空为不鉴权",
  "sanitize-dump-payload": "RESTORE/加载时是否深度校验负载",
  "save": "RDB 自动保存条件(秒 变更数)",
  "server_cpulist": "主线程绑定的 CPU 核",
  "set-max-intset-entries": "整数 set 使用 intset 编码的最大元素数",
  "set-proc-title": "是否动态修改进程标题",
  "slave-announce-ip": "replica-announce-ip 的旧别名",
  "slave-announce-port": "replica-announce-port 的旧别名",
  "slave-ignore-maxmemory": "replica-ignore-maxmemory 的旧别名",
  "slave-lazy-flush": "replica-lazy-flush 的旧别名",
  "slave-priority": "replica-priority 的旧别名",
  "slave-read-only": "replica-read-only 的旧别名",
  "slave-serve-stale-data": "replica-serve-stale-data 的旧别名",
  "slaveof": "启动时设定的主库地址",
  "slowlog-log-slower-than": "慢查询记录阈值(微秒)，负数为关闭",
  "slowlog-max-len": "慢查询日志保留条数",
  "stop-writes-on-bgsave-error": "RDB 保存失败时是否拒绝写入",
  "stream-node-max-bytes": "Stream 单节点最大字节数",
  "stream-node-max-entries": "Stream 单节点最大条目数",
  "supervised": "与 systemd/upstart 的集成方式",
  "syslog-enabled": "是否输出到 syslog",
  "syslog-facility": "syslog 设施名",
  "syslog-ident": "syslog 标识",
  "tcp-backlog": "TCP 半连接队列长度",
  "tcp-keepalive": "TCP keepalive 探测间隔(秒)",
  "timeout": "客户端空闲多少秒后断开，0 为不断开",
  "tls-auth-clients": "是否要求客户端证书",
  "tls-ca-cert-dir": "CA 证书目录",
  "tls-ca-cert-file": "CA 证书文件",
  "tls-cert-file": "服务端证书",
  "tls-ciphers": "TLSv1.2 及以下加密套件",
  "tls-ciphersuites": "TLSv1.3 加密套件",
  "tls-client-cert-file": "作为客户端时的证书",
  "tls-client-key-file": "作为客户端时的私钥",
  "tls-client-key-file-pass": "客户端私钥口令",
  "tls-cluster": "集群总线是否启用 TLS",
  "tls-dh-params-file": "DH 参数文件",
  "tls-key-file": "服务端私钥",
  "tls-key-file-pass": "服务端私钥口令",
  "tls-port": "TLS 监听端口，0 为关闭",
  "tls-prefer-server-ciphers": "是否优先使用服务端套件顺序",
  "tls-protocols": "允许的 TLS 版本",
  "tls-replication": "复制链路是否启用 TLS",
  "tls-session-cache-size": "TLS 会话缓存条数",
  "tls-session-cache-timeout": "TLS 会话缓存超时(秒)",
  "tls-session-caching": "是否启用 TLS 会话复用",
  "tracking-table-max-keys": "客户端缓存追踪表的最大键数",
  "unixsocket": "Unix socket 路径",
  "unixsocketperm": "Unix socket 权限",
  "use-exit-on-panic": "panic 时用 exit 而非 abort(便于容器重启)",
  "watchdog-period": "看门狗周期(毫秒)，调试用",
  "zset-max-ziplist-entries": "zset 使用紧凑编码的最大元素数",
  "zset-max-ziplist-value": "zset 使用紧凑编码的最大值长度"
}

/** 取配置项默认值；未收录返回 undefined，由调用方决定展示成 "-" */
export function getRedisConfigDefault(name?: string): string | undefined {
  const key = (name ?? "").trim().toLowerCase()
  return key ? REDIS_CONFIG_DEFAULTS[key] : undefined
}

/** 取配置项说明；未收录返回 undefined */
export function getRedisConfigDescription(name?: string): string | undefined {
  const key = (name ?? "").trim().toLowerCase()
  return key ? REDIS_CONFIG_DESCRIPTIONS[key] : undefined
}

/**
 * 当前值是否与默认值不同。
 *
 * 默认值未收录时一律返回 false —— 不能把"我们不知道"当成"被改过"，
 * 否则「仅显示变动值」会把大量未知项混进来。
 */
export function isRedisConfigChanged(name: string, value: string): boolean {
  const def = getRedisConfigDefault(name)
  if (def === undefined) return false
  return (value ?? "").trim() !== def.trim()
}

/**
 * 值为凭据的配置项：表格里以掩码展示。
 *
 * 「仅显示变动值」会把设过密码的实例的 requirepass / masterauth 顶到最前面，
 * 明文铺在表格里很容易随截图外泄。需要查看/修改密码请走「集群密码修改」。
 */
const SENSITIVE_CONFIGS = new Set([
  "requirepass",
  "masterauth",
  "tls-key-file-pass",
  "tls-client-key-file-pass"
])

/** 凭据类配置的展示值；非敏感项原样返回。仅影响展示，不影响与默认值的比对 */
export function maskRedisConfigValue(name: string, value: string): string {
  if (!SENSITIVE_CONFIGS.has((name ?? "").trim().toLowerCase())) return value
  return (value ?? "").trim() ? "******" : value
}
